// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO60x2ClUxPawdNtduLcFmPF1cig_ED0I',
    appId: '1:587058548407:web:915264c9bd10fa66bdc732',
    messagingSenderId: '587058548407',
    projectId: 'altwally-16812',
    authDomain: 'altwally-16812.firebaseapp.com',
    storageBucket: 'altwally-16812.appspot.com',
    measurementId: 'G-0QHLJY736W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvK9QuEIVcV7gindIKtGHbnHSbGIyem0g',
    appId: '1:587058548407:android:1f4b48fe82548da3bdc732',
    messagingSenderId: '587058548407',
    projectId: 'altwally-16812',
    storageBucket: 'altwally-16812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhXDYMQv4PIDdzNm5fXICnefB_xRhT5jc',
    appId: '1:587058548407:ios:eac452e7d0f4ab14bdc732',
    messagingSenderId: '587058548407',
    projectId: 'altwally-16812',
    storageBucket: 'altwally-16812.appspot.com',
    iosBundleId: 'com.example.altWally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhXDYMQv4PIDdzNm5fXICnefB_xRhT5jc',
    appId: '1:587058548407:ios:2381e6c89762467ebdc732',
    messagingSenderId: '587058548407',
    projectId: 'altwally-16812',
    storageBucket: 'altwally-16812.appspot.com',
    iosBundleId: 'com.example.altWally.RunnerTests',
  );
}
